### ISSUE TITLE
Support for unraid docker

### ISSUE THREAD

**Issue by dorgan** [ntodd/video_transcoding_docker#2]
It seems when running this docker from the command line of a docker server even when passing `--cpuset-cpu=0-23` transcoding is EXTREMELY slow, to the point where it will take 24+ hours to transcode BD.

**Comment by ntodd** [comment]
Sorry, I don't have an Unraid install to test this on. I'll leave the issue open in case anyone else can assist.

**Comment by klogg416** [comment]
I have an unRAID rig and can test it tomorrow. Can you reply with any
set up variables so I can mirror your config?
/kyle

On Tue, Jan 2, 2018, at 10:00 AM, Nate Todd wrote:
> Sorry, I don't have an Unraid install to test this on. I'll leave the
> issue open in case anyone else can assist.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/ntodd/video_transcoding_docker/issues/2#issuecomment-354784445

**Comment by klogg416** [comment]
@dorgan I loaded up the container with default settings and transcoded a movie (default options with --prefer-ac3). unRAID shows 4 cores/8 threads at 100% and an avg fps just above 30, or a little faster than real time.

unRAID version 6.4.0_rc18f
ntodd container tag :latest, installed today.

Not sure what else to tell you but the container and unRAID are performant for me.
/kyle

**Comment by ntodd** [comment]
@klogg416 Thanks for checking on this!

**Comment by klogg416** [comment]
@ntodd yeah, you bet. Thanks for making the Container. 👍 

@dorgan, I meant to say that the CPU is a Intel I7 3770, so 4c/8t is fully utilized.

**Comment by dorgan** [comment]
ok it now appears to be working after a system restart.  it would be easier if i could just attach to the container when I want to use it, instead of having to start a new one every time from the command line.  because then I have to remove the old container everytime

**Comment by dorgan** [comment]
If i was to use this Dockerfile and then have it launch a script to transcode all MKV's in a given directory how would I do that?  just using FROM? and then CMD to the script?

**Comment by dorgan** [comment]
i am now using this are a reference for my docker container, thanks!
